### PR TITLE
Change WindowsProvider permission scope separator to space

### LINKED ISSUE #192: WindowsProvider uses deprecated range separator
## Describe the bug
In [WindowsProvider](https://github.com/CommunityToolkit/Graph-Controls/blob/main/CommunityToolkit.Authentication.Uwp/WindowsProvider.cs#L546), use `,` as scopes separator, while in [graph documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent#requesting-individual-user-consent), space is recommended. This problem will cause the AAD account to fail to authorize when requesting multiple permissions.

- [ ] Is this bug a regression in the toolkit?  If so, what toolkit version did you last see it work:

## Steps to Reproduce

*To reproduce this error, you need to prepare an AAD account and grant two or more permissions*

1. Enter ClientId and two or more scopes according to the documentation
2. Click the Login button to log in to your AAD account
3. See error

## Expected behavior
Can request multiple permissions normally.

## Environment

```
NuGet Package(s): 7.1.2

Package Version(s): 7.1.2

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [x] Insider Build (build number: 22000)

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [x] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [x] Insider Build (22000)

Device form factor:
- [x] Desktop
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [ ] 2017 (version: )
- [ ] 2019 (version: ) 
- [x] 2022

```

## Additional context
It's a bit quirky, but when using `,` MSA works fine and AAD fails. With spaces, both work fine

### PR DESCRIPTION
**Pull request by Richasy**
Fixes #192 

## PR Type

What kind of change does this PR introduce?

- Bugfix

## What is the current behavior?

Failed when trying to grant AAD multiple permissions

## What is the new behavior?

Grant AAD account multiple permissions normally

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tested code with current [supported SDKs](https://github.com/CommunityToolkit/Graph-Controls/blob/main/README.md)
- [ ] Sample in sample app has been added / updated (for bug fixes / features)
  - [ ] Icon has been created (if new sample) following the [Thumbnail Style Guide and templates](https://github.com/CommunityToolkit/WindowsCommunityToolkit-design-assets)
- [ ] Tests for the changes have been added (for bug fixes / features) (if applicable)
- [x] Header has been added to all new source files (run _build/UpdateHeaders.bat_)
- [x] Contains **NO** breaking changes

### CODE REVIEW

**Comment by Richasy** [comment]
@shweaver-MSFT  Here are the error message: 

> Login failed: Failed
Login failed: 3399614466: AADSTS65002: Consent between first party application '{my-app-client-id}' and first party resource '00000003-0000-0000-c000-000000000000' must be configured via preauthorization - applications owned and operated by Microsoft must get approval from the API owner before requesting tokens for that API.
Trace ID: 72841998-32b2-46ec-ad49-e804e9d22000
Correlation ID: 9bb2e503-2bbe-4cb2-acb2-3b854f60cbe0
Timestamp: 2022-06-22 02:49:19Z

Code here:

```csharp
// string[] RequestScopes = { "User.Read", "Tasks.ReadWrite" };
var webAccountProviderConfig = new WebAccountProviderConfig(WebAccountProviderType.Any, Constants.GraphClientId);
var authProvider = new WindowsProvider(RequestScopes, webAccountProviderConfig);
```

I hide the `ClientId`. 
It seems that AAD provider and MSA provider treat `scope` a little differently. We expected two permissions, `A` and `B`, but after connecting with a comma, AAD provider recognized it as one permission, namely `A,B`, obviously we do not have this permission, so the error message returned is not pre-authorized

**Review by Arlodotexe — APPROVED** [review]
Did some digging through the source code for MSAL. They mostly deal with scopes in an `IEnumerable<string>`, but when parsing for a request they use spaces as a separator: 

[This extension method](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/35287730c8a55092e707ef024af38daed88d2773/src/client/Microsoft.Identity.Client/Utils/EnumerableExtensions.cs#L25) is used to create the scopes for most (maybe all) requests:

image

**Comment by michael-hawker** [comment]
image

Posting the image of that function here as well for full context, nice find @Arlodotexe, still would be good to know where that's called out in the docs. Following up with the Graph doc team.

**Review by michael-hawker — APPROVED** [review]

**Comment by michael-hawker** [comment]
Ah, got pointed to the doc finally here: https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc#send-the-sign-in-request

> A space-separated list of scopes.

**Pull request merged**
