### PR TITLE
Fixes race condition issue with OnProviderStateChanged event.

### LINKED ISSUE #124: Race condition issue when subscribing to ProviderStateChanged
## Describe the bug
There is a race condition issue when subscribing to `ProviderManager.Instance.ProviderStateChanged`. Currently this only works if you do this before `ProviderManager.Instance.GlobalProvider` is setup.

## Steps to Reproduce
It is easy to see this in the UwpMsalProviderSample project. Change the constructor of `LoginButton` to this:

        public LoginButton()
        {
            InitializeComponent();

            _ = Task.Run(async () =>
            {
                await Task.Delay(2000);

                _ = Windows.ApplicationModel.Core.CoreApplication.MainView.CoreWindow.Dispatcher.RunAsync(CoreDispatcherPriority.Normal, () =>
               {
                   ProviderManager.Instance.ProviderStateChanged += (s, e) => UpdateState();
                   UpdateState();
               });
            });
        }

Now when the application is executed the text on the sign in button will not be updated.
 
## Expected behavior
It should not matter when you subscribe to `ProviderManager.Instance.ProviderStateChanged`.

## Additional context
I will create an PR for this.

### PR DESCRIPTION
**Pull request by pekspro**
Fixes #124

## PR Type

Bugfix

### CODE REVIEW

**Comment by shweaver-MSFT** [comment]
Hey @pekspro, thanks for submitting this! The fix looks great. I'm not sure what is up with the build failure, but I'm experiencing the same issue on the main WCT repo as well. @michael-hawker any idea what's going on with the build CI?

**Comment by shweaver-MSFT** [comment]
@pekspro, we figured out the build issue. It was caused by a recent org name change in WCT, and the fix  has been pushed to main branch. Please fetch the latest from main to get the build fixed up.

**Comment by pekspro** [comment]
Thanks @shweaver-MSFT. I have synced the code and now it compiles :-)

**Review by shweaver-MSFT — APPROVED** [review]

**Comment by shweaver-MSFT** [comment]
Looks good! Merging in now

**Pull request merged**
